### ISSUE TITLE
Name pattern for criterion functions.

### ISSUE THREAD

**Issue by tobiasraabe** [OpenSourceEconomics/estimagic#112]
### Current situation

In #107 we implemented an interface for the estimation via maximum likelihood. Since the criterion function does not return a scalar and instead the log likelihood contributions, we chose ``log_like_obs`` as a preliminary name for the criterion function in ``estimate.py``.

### Desired Situation

At least, we should have brainstormed a little bit whether we would like to have unique names for the criterion functions for different estimation techniques and the general maximize and minimize interface. Couple of notes:

* The naming is probably limited to ``estimate.py`` as the estimation functions can reuse ``maximize()`` and ``minimize()`` and other functions.
* Having a different name for the public interface highlightens the fact that the function needs a different criterion function than ``maximize()`` and ``minimize()``.

### Proposed implementation

Again only preliminary notes.

* We might want to have the same name for GMM, MSM, and ML which would be something like ``contributions``.
* Maybe we also want to have unique name for not closely-related concepts such as ``log_like_obs`` for ML and ``moments`` for GMM and MSM.

**Comment by hmgaudecker** [comment]
Haha, you beat me to it :-)

https://github.com/OpenSourceEconomics/estimagic/pull/107#discussion_r363098008

**Comment by tobiasraabe** [comment]
Moved comment from @hmgaudecker in https://github.com/OpenSourceEconomics/estimagic/pull/107#discussion_r363098008
> I think it definitely should have a plural in there. And then a clear docstring stating that this is supposed to be an array of log-likelihood contributions (I am mostly guessing here). criterions_per_obs ? That should work for GMM & friends, too.

**Comment by janosg** [comment]
The new interface is that the criterion function can either be a scalar float or a dictionary containing the entries `"value"`, `"contributions"` (which produce the value if summed up) and `"root_contributions"` (which produce the value if squared and then summed up). This is the only way how one can try optimizers like `bobyqa` and `pounders` with changing only one argument. 

For the criterion function for a likelihood estimation is then simply called `log_likelihood`. 

@tobiasraabe @hmgaudecker can I close this?

**Comment by hmgaudecker** [comment]
Sure!
