### ISSUE TITLE
Improve the results returned by minimize and maximize

### ISSUE THREAD

**Issue by roecla** [OpenSourceEconomics/estimagic#114]
### Current Situation

1. in the `results` dictionary the `status` value is always set to "success" when the optimization finishes. This results in unwanted behavior (e.g. status is set to "success" when scipy stops after the maximum number of iterations).

2. in `_process_scipy_results` entries like the Jacobian are saved twice, once under the unified name and once under the original name.

3. The results dictionary does not contain a path to the database. 

4. We still `fitness` as the name of the final criterion value and `x` for the parameter vector.

5. At the moment all internal columns that start with `_` are returned to the user in the final `params` DataFrame as well. Do we want this? 

### Desired Situation

1. status is only set to "success" if the optimizer claims to have successfully finished. In addition, we might want to check that the current function evaluation is the lowest one recorded in the database.

2. Not sure if this is the behavior we want. One the one hand people coming from scipy might appreciate that they can use the results object as before. One the other hand it is duplication and users might wonder if the entries refer to different concepts and just happen to be the same.

3. The results dictionary should include this.

4. I would suggest `criterion_value` and `final_internal_params`. 

5. I would propose to remove all private (i.e. starting with a `_`) columns before returning `params` to the user.

**Comment by janosg** [comment]
All of this is done.
