### ISSUE TITLE
Using dashboard within waf-process causes waf to never terminate

### ISSUE THREAD

**Issue by Johannes-Ewald** [OpenSourceEconomics/estimagic#116]
### Bug description

I am using skillmodels integrated in a waf-process to analyse some HRS data. Calling the fit method of SkillModel with `dashboard=True` opens up the dashboard as expected, but prevents the waf-process from finishing. That means I do not receive the 'build' finished succesfully message. I expected the waf-process to finish after ~3 hours on my computer (runtime with `dashboard=False`). The python script runs correctly and returns a csv-file in both cases.

### To Reproduce
`mod = SkillModel(model_dict=model_dict, dataset=dataset, model_name="baseline", dataset_name="hrs")`
`res = mod.fit(start_params=start_params, dashboard=True, algo_options={"ftol": 1e-5})`

### Expected behavior

I expected the waf-process to finish the build after ~3 hours. It did not finish after 8-9 hours even tough the expected output was saved in the bld-folder.

### System

 - OS: Windows 10
 - Version 0.0.25

**Comment by roecla** [comment]
Using the `database_dashboard` branch, this should be resolved now in several ways:

1. You can just write a simple dashboard script with the following code: 

```python
from estimagic.dashboard.run_dashboard import run_dashboard

if __name__ == "__main__":
    run_dashboard(
        [
            "path/to/your_first_database.db",
            "path/to/your_second_database.db",
            ...
        ])
```
(There will be a command line interface for this later on.) 

Then you can call this script after your optimization has started (or even after it has finished) outside of `waf`.

2. You can start the dashboard from within `maximize` or `minimize` by setting `dashboard` to True. This should work out of the box and should not keep `waf` running as the dashboard process is terminated once the optimization finishes unless you set `keep_dashboard_alive` in the `general_options` to True.

It would be great if you could go to the branch and try that the new version really fixes this issue and report back here.
