### ISSUE TITLE
Document `general_options` for optimization

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/estimagic#126]
### Problem

general options are not documented: https://estimagic.readthedocs.io/en/latest/optimization/general_options.html

### Options to document

- [ ] `criterion_exception_raise` 
- [ ] `criterion_exception_penalty`

@tobiasraabe, did I forget other options?

**Comment by tobiasraabe** [comment]
n_cores? And gradient options are not documented either.

**Comment by tobiasraabe** [comment]
n_cores is a little bit difficult. I would set it to either -1 or -2 by default. I think -1 uses all cores and -2 all cores -1. https://joblib.readthedocs.io/en/latest/generated/joblib.Parallel.html

**Comment by janosg** [comment]
Outdated.
