### ISSUE TITLE
maximum_likelihood_estimation notebook throws Error

### ISSUE THREAD

**Issue by roecla** [OpenSourceEconomics/estimagic#134]
### Bug description

When running `maximum_likelihood_estimation.ipynb` on my local machine, I get the following Error:

![image](https://user-images.githubusercontent.com/9567321/74603495-4e869680-50b4-11ea-9cbd-2b1d9863e7e7.png)

**Comment by ChristianZimpelmann** [comment]
Same problem.

**Comment by janosg** [comment]
I cannot reproduce this with estimagic `0.0.28`. Can @roecla or @ChristianZimpelmann test it again after I make the release later today?

**Comment by roecla** [comment]
I think it was fixed in the CLI PR by @tobiasraabe.

**Comment by roecla** [comment]
Verified that it's fixed now.
