### ISSUE TITLE
Arguments for linear inequality constraints unintuitive

### ISSUE THREAD

**Issue by ChristianZimpelmann** [OpenSourceEconomics/estimagic#138]
### Bug description

If I specify a linear constraint like
`{"loc": "b", "type": "linear", "weights": 1 / 3, "lower": 3}`
I read in my head `b-values lower 3`. What is actually specified is however `b-values greater than 3`.

### Expected behavior

I suggest naming the argument "lower_bound" instead of "lower" and "upper_bound" instead of  "upper" to avoid the misunderstanding.

**Comment by janosg** [comment]
The original motivation for this was that in params we also call the bound columns just `"lower"` and `"upper"`, but I see your point and think we should change it. The question is if we then also rename it in params. The current name could be confusing once we get a `"ci_lower"` and `"ci_upper"` column for confidence intervals.

**Comment by hmgaudecker** [comment]
+1 on removing ambiguity at the expense of longer column identifiers, too.

**Comment by ChristianZimpelmann** [comment]
I would change it in params, too.

**Comment by janosg** [comment]
I would also change it in params, but accept both for a while and emit a DeprecationWarning if the short names are used. The right place for the warning is probably [here](https://github.com/OpenSourceEconomics/estimagic/blob/0b31adacf2e251d4a2f4ca2f50247191c6381226/estimagic/optimization/transform_problem.py#L273)

**Comment by ChristianZimpelmann** [comment]
Just to be sure. I assume we would like to do the same change `lower` -> `lower_bound` for parameter bounds?
