### ISSUE TITLE
"upper" column in parameter df with new pandas integer extension type, produces error

### ISSUE THREAD

**Issue by ChristianZimpelmann** [OpenSourceEconomics/estimagic#139]
### Bug description

If the "upper" column in a params df is of the new pandas integer extension type, `.to_numpy()` in `_internal_bounds_from_params` returns an array of type object which produces the error below.

### To Reproduce

```
data = pd.read_pickle("ologit.pickle")
formula = "apply ~ pared + public + gpa"
params, y, x, constr = ordered_logit_processing(formula, data)
params["lower"] = -20.
params["upper"] = 1

# Convert to new extension type
params = params.convert_dtypes()
res = maximize(
    criterion=ordered_logit_loglike, 
    params=params, 
    algorithm='scipy_L-BFGS-B',
    constraints=[],
    criterion_kwargs={"y": y, "x": x}, 
    dashboard=False
)
```

### Expected behavior

No error

### Screenshots/Error messages

```
~/miniconda3/envs/ambig-beliefs/lib/python3.7/site-packages/estimagic/optimization/scipy.py in minimize_scipy_np(func, x0, bounds, algo_name, algo_options, gradient)
     25     # and requires a list of tuples for each parameter with lower and upper bound.
     26     bounds = np.column_stack(bounds)
---> 27     mask = ~np.isfinite(bounds)
     28     bounds = bounds.astype("object")
     29     bounds[mask] = None

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

### System

 - OS: [e.g. Ubuntu 18.04]
 - Version [e.g. 0.0.1]

**Comment by ChristianZimpelmann** [comment]
This is probably an error that needs to be fixed by numpy.

**Comment by janosg** [comment]
Would this be solved if we convert bounds to float, as we already do with the value column? If so, we should add this conversion [here](https://github.com/OpenSourceEconomics/estimagic/blob/1b2a8770d8c5cbbd4eea9088f7e7d07cea4a7d64/estimagic/optimization/optimize.py#L628) after Klara finished her current PR (which refactors the whole arguments processing for the optimizations). Converting the bounds to float is probably safer anyways for optimizers like pounders.

**Comment by ChristianZimpelmann** [comment]
That should solve it. Let me know once Klara is finished, I can take care of it.

**Comment by janosg** [comment]
I merge Klara's PR later today. Thanks for solving this.
