### ISSUE TITLE
RTD / edit still points to github/janosg

### ISSUE THREAD

**Issue by hmgaudecker** [OpenSourceEconomics/estimagic#140]
### Bug description / Reproducer

Click this link:

https://estimagic.readthedocs.io/en/latest/

Link at "Edit on GitHub" is outdated:

https://github.com/janosg/estimagic/blob/master/docs/source/index.rst

**Comment by roecla** [comment]
This had to changed in the ReadTheDocs settings. Now the links point to OpenSourceEconomics.
