### ISSUE TITLE
Add pounders algorithm to our optimizers

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/estimagic#15]
https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Tao/TAOPOUNDERS.html

Best way to do that is probably [petsc4py](https://anaconda.org/conda-forge/petsc4py/files) but the [documentation](https://www.mcs.anl.gov/petsc/petsc4py-current/docs/usrman/overview.html#petsc-efficient) is very incomplete. 

The relevant import seems to be: `from petsc4py.PETSc import TAO`

**Comment by tobiasraabe** [comment]
While implementing, make sure that ``algo_options`` are passed down to the optimizer.
