### ISSUE TITLE
estimagic raises exception if criterion value is a series.

### ISSUE THREAD

**Issue by tobiasraabe** [OpenSourceEconomics/estimagic#155]
* estimagic version used, if any:
* Python version, if any:
* Operating System:

### What would you like to enhance and why? Is it related to an issue/problem?

The exception happens in `expand_criterion_output` if the first criterion value is a series instead of a NumPy array. Both objects are very similar and should be treated the same way.

This happens while using Pounders and returning a series of moment errors.

### Describe the solution you'd like

We can probably add `pd.Series` to the `isinstance` call.

**Comment by janosg** [comment]
This is solved and tested.
