### ISSUE TITLE
Cannot save criterion arrays to database.

### ISSUE THREAD

**Issue by tobiasraabe** [OpenSourceEconomics/estimagic#156]
### Bug description

It happened while estimating models with Pounders. The moment errors cannot be saved to the database because the table for criterion values is suited for scalars

### To Reproduce

Estimate with pounders.

### Screenshots/Error messages

*Will follow soon.*

### System

 - OS: WLS on Windows 10
 - Version 0.0.29

**Comment by janosg** [comment]
Solved in estimagic 0.1
