### ISSUE TITLE
POUNDERs docstring mixed up? 

### ISSUE THREAD

**Issue by hmgaudecker** [OpenSourceEconomics/estimagic#190]
### Bug description

https://estimagic.readthedocs.io/en/latest/how_to_guides/optimization/how_to_specify_algorithm_and_algo_options.html#algorithms-from-the-toolkit-for-advanced-optimization-tao

- absolute_gradient_tolerance (float) – Stop if relative norm of gradient is less than this. If set to False the algorithm will not consider absolute_gradient_tolerance.
- relative_gradient_tolerance (float) – Stop if norm of gradient is less than this. If set to False the algorithm will not consider relative_gradient_tolerance.

Looks reversed to me?

**Comment by janosg** [comment]
Solved in #208
