### ISSUE TITLE
"Supported algorithms" should be more prominent in docs

### ISSUE THREAD

**Issue by hmgaudecker** [OpenSourceEconomics/estimagic#191]
This is crucial information that many users will want to access frequently:

https://estimagic.readthedocs.io/en/latest/how_to_guides/optimization/how_to_specify_algorithm_and_algo_options.html#supported-algorithms

It is not even present in the table of contents and I have only been able to locate it based on messages with a precise link (using various searches did not help).

My suggestion would be:
- Add an entry at the level of "Tutorials", "How-To-Guides" etc., maybe one below, but extremely visible
- Call it "available optimizers"
- Any way to add tags for searches (optimizers, algorithms, ...)

**Comment by janosg** [comment]
Solved in #208
