### ISSUE TITLE
Even more dashboard improvements

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/estimagic#21]
**Plans:**

- pass through of basic server options (such as the port)
- try random port if one port is occupied
- Better position of legend

**Comment by Eric-Sommer** [comment]
Something is strange with the bokeh server. Your `minimize_example` works only once. After starting a second time, I get `CRITICAL:bokeh.command.util:Cannot start Bokeh server, port 5039 is already in use`

**Comment by janosg** [comment]
For now you will have to do a Kernel restart in your notebook before you re-run the optimization  but @roecla  is working on the issue.

**Comment by janosg** [comment]
This is all solved.
