### ISSUE TITLE
Unify usage of `p_value` / `pvalue`

### ISSUE THREAD

**Issue by hmgaudecker** [OpenSourceEconomics/estimagic#220]
### Bug description

`p_value` and `pvalue` are used as column names in different places; may lead to errors.

### To Reproduce

`estimagic.inference.likelihood_inference.do_likelihood_inference` returns table with column `p_value`
`estimagic.visualization.estimation_table` expects table with column `pvalue` and returns KeyError

### System

 - OS: Ubuntu 20.04
 - Version 0.1.3

**Comment by hmgaudecker** [comment]
I'd suggest `p_value` everywhere, but I suspect `pvalue` has been mostly used for compatibility with statsmodels? Thought it was a matter of a quick search & replace, but I'll rather not mess with it then until someone provides more information.

**Comment by janosg** [comment]
I am also in favor of using `p_value` for everything that does not work directly with a statsmodels results object.
