### ISSUE TITLE
Reduce Overhead

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/estimagic#236]
### What would you like to enhance and why? Is it related to an issue/problem?

Most of the time the small estimagic overhead does not matter, but for toy problems and unit tests it would be nice to reduce it even further

### To-Do

- [x] Reduce calls to `process_constraints` by adding `is_processed` flag to the functions in `parameter_conversion.py` and calling them with processed inputs where possible.

**Comment by tobiasraabe** [comment]
Two profiles from very small optimizations with lfbgsb, with estimagic and bare scipy, with criterion_and_derivatives. The difference is 85ms to 8ms.

[profiles.zip](https://github.com/OpenSourceEconomics/estimagic/files/7512187/profiles.zip)

**Comment by janosg** [comment]
Thanks for the profile. I think we could get from factor 10 to about 1.5 with minor changes. Most time is spent on constraints handling even though you do not have constraints. We can simply bypass that earlier.

**Comment by janosg** [comment]
Reached a speed up of about 20x for a minimal example without constraints. Now we have reached the point where simple operations on the params DataFrame (setting dtype "value" and bounds columns, doing some simple checks, making a copy before overwriting "value" column) are responsible for most of the remaining overhead. 

Given estimagic's target group I would leave it at that. Once we make the `params` argument more flexibel (just numpy array, pytrees), we can tackle the rest.

**Comment by janosg** [comment]
Solved with the move to pytrees.
