### ISSUE TITLE
Implement user feedback

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/estimagic#253]
- [x] Improve documentation of pairwise equality constraints (HM)
    - [x] Better example using MultiIndex
    - [x] Mention that selected parameters are matched by position 
    - [x] Mention that selections need to have same length 
- [x] Improve error message that occurs when function fails at a place where derivative is already evaluated or the other way round. Just mention the error cannot be captured, not why and show the error that occurred with less clutter around it. (Tobi)
- [x] Re-sort columns of solution parameters 
- [x] Add "free" indicator to solution parameters (HM) [obsolete with pytrees]
- [x] scipy least squares optimizers have `_tol` where it should be `_tolerance`. 
- [x] Add utility function to get number of free parameters from params and constraints (HM)
- [x] API ref on estimate_ml needs a better description of the dictionary that is returned (HM) superseeded by #337 
- [x] Make sure there is a way to skip the standard error calculation in estimation functions and document it. (HM)
- [x] Make regression table importable directly from estimagic and use it in the estimation tutorials 
- [x] Make a better documentation notebook on the least squares solvers. It should also contain a formal definition of least squares problems and some pointers to literature. (Jacek)
- [x] Parallelize the function evaluations for univariate effects (Jacek)
- [x] Typos in keys of numdiff options during optimization do not raise errors (Janos)

**Comment by hmgaudecker** [comment]
Docs error:

```
UserWarning: LaTeX compilation requires the package siunitx and adding
                    \sisetup{input_symbols =()} to your main tex file. To turn
                    this warning off set value of siunitx_warning = False
```

Most importantly: One error later I found out it is `input-symbols` (minus sign, not underscore).

Overall suggestion:

```
UserWarning: LaTeX compilation requires the package siunitx. 
Make sure your preamble contains:

\usepackage{siunitx}
\sisetup{input-symbols=()} 

To turn this warning off, set 

siunitx_warning=False

when calling estimation_table.
```

**Comment by hmgaudecker** [comment]
You may also want a check for underscores in variable names and/or add an option to convert them (sorry if I missed it!)
