### ISSUE TITLE
Dashboard fails with large starting values or large initial fitness

### ISSUE THREAD

**Issue by roecla** [OpenSourceEconomics/estimagic#30]
When the dashboard is started with an extremely high value (order 1e17) the dashboard opens an empty tab with just the tab rider but with no plot. It also does not throw an Error. 

When extremely high values are added to the ColumnDataSource later the dashboard does handle them (at least up to 1e20).

**Comment by tobiasraabe** [comment]
This is solved, right?

**Comment by janosg** [comment]
Not sure. @roecla ?

**Comment by roecla** [comment]
Yes, this is solved.
