### ISSUE TITLE
Fix conda release

### ISSUE THREAD

**Issue by hmgaudecker** [OpenSourceEconomics/estimagic#301]
- Badge in README still points to [opensourceeconomics conda channel](https://anaconda.org/OpenSourceEconomics/estimagic) with v0.1.3
- v0.2.3 has not made it to [conda-forge yet](https://anaconda.org/conda-forge/estimagic) (just normal lag or process not initialised?)
- Somewhat beyond scope here, but while somebody is at it: I would suggest retiring https://anaconda.org/OpenSourceEconomics/ or at least deleting some stuff like [pipeline](https://anaconda.org/OpenSourceEconomics/pipeline) (I'd like to think I was the only user, ever :smile:)

**Comment by janosg** [comment]
Regarding `0.2.3`, it's the normal lag. 

Would be happy to delete the OSE conda channel but we'll have to ask around if anybody is still using that. I think ruspy requires a pretty old estimagic, for example.

**Comment by janosg** [comment]
Badges are updated in #302
