### ISSUE TITLE
Improve estimation code

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/estimagic#316]
### Problems

1. The estimation code does not yet work with general pytrees 
2. I always do the optimization outside of `estimate_ml` and most other users do the same. It just becomes too complicated to specify all relevant inputs for optimization and inference in one function. 
3. Numerical hessians are not yet used in estimation functions and closed form hessians raise an error (as far as I know)

### Proposed solution

1. Deprecate `estimate_ml` and `estimate_msm`
2. Replace them by `do_ml_inference` and `do_msm_inference` which do just the inference part of `estimate_ml` and `estimate_msm`. 
3. Implement a function to generate summary pytrees as described [here](https://estimagic.readthedocs.io/en/latest/development/eep-01-pytrees.html#format-1-everything-becomes-a-dataframe)
3. Add general pytree support to the estimation functions. Most of this will be trivial and the results are already calculated. Just the format needs to be converted.

**Comment by hmgaudecker** [comment]
Well, you tend to have complicated models and know the internals.

Large majority of people will just use defaults no matter what.

Unless there are name clashes and defaults you want to set differently between optimization/inference, I would not depreciate the current stuff but leave it as a shorthand.

**Comment by janosg** [comment]
Ok, I also heard from a few other people now that they like the one step estimation function so we keep that.

**Comment by timmens** [comment]
Done with #330.
