### ISSUE TITLE
Move documentation to MyST

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/estimagic#320]
### What would you like to enhance and why?

Move the documentation to MyST instead of Restructured Text. It is just much simpler to write markdown compared to rst. 

### Resources 

- [Example PR](https://github.com/pytask-dev/pytask/pull/232/files/f8e5316862fa8bfb9c615ab3397ea1bc7679963c..03871ebdcda0983614173e1778d895ac2ce0c1f4) where Tobi has done it
- https://myst-parser.readthedocs.io/en/latest/sphinx/intro.html

**Comment by timmens** [comment]
Do this alongside https://github.com/OpenSourceEconomics/econ-project-templates/pull/98.
