### ISSUE TITLE
Improve documentation of numerical derivatives

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/estimagic#322]
## We need the following things

- [x] A notebook in the `getting_started`, similar to the first_optimization notebook that shows how to calculate basic first and second derivatives, how to parallelize and how to use pytree params in derivatives (including the result format when params are pytrees)
- [x] A how to guide for second derivatives 
- [x] Split the derivative plot part into a separate how to guide

**Comment by timmens** [comment]
Do Examples:

1. Numpy
2. PyTree (from getting_started optimization)
3. n_cores
4. first_derivative does everything, scalar, jacobian, etc.

**Comment by janosg** [comment]
Solved with #326
