### ISSUE TITLE
Improve error message for optional algorithms

### ISSUE THREAD

**Issue by hmgaudecker** [OpenSourceEconomics/estimagic#334]
* estimagic version used, if any: 0.2.3

### What would you like to enhance and why? Is it related to an issue/problem?

Attempting to use `fides` optimizer while not having it installed. 

Error:

```pytb
ValueError: Invalid algorithm: fides. Did you mean ['pounders', 'neldermead_parallel', 'scipy_bfgs']?
```

### Describe the solution you'd like

Something like:

```pytb
ImportError: Missing optional dependencies ['fides']
```
Potentially with recipe how to install it or pointer to docs with instructions.

**Comment by janosg** [comment]
Thanks! This is already fixed but the fix is not released yet. The Error you will get after next release is:

```python
NotInstalledError: "The 'fides' algorithm requires the fides package to be installed. You can install it with `pip install fides>=0.7.4`."
```

**Comment by hmgaudecker** [comment]
Great, thanks!
