### ISSUE TITLE
Automatically open dashboard in browser.

### ISSUE THREAD

**Issue by tobiasraabe** [OpenSourceEconomics/estimagic#39]
Sure, it is not much to ask the user to copy-paste the localhost link, but it is more convenient, if the dashboard is opened automatically in another tab.

There is a stdlib module for that called ``webbrowser``. Just insert

```
import webbrowser

webbrowser.open("http://localhost:2321")
```

From my experience, ``"http"`` seems necessary at least on Windows.

**Comment by janosg** [comment]
Actually, on all Computers we tried, the dashboard does open automatically. Can you describe where it didn't?

- OS:
- Dashboard run from notebook or script:

**Comment by tobiasraabe** [comment]
#UserError
