### ISSUE TITLE
Add Bayesian bootstrap

### ISSUE THREAD

**Issue by timmens** [OpenSourceEconomics/estimagic#392]
### What would you like to enhance and why? Is it related to an issue/problem?

Currently, estimagic only supports the standard bootstrap. The Bayesian bootstrap ([Rubin, 1980](https://www.jstor.org/stable/2240875?seq=1)) provides an alternative with good theoretical properties in both a Bayesian and frequentist world. A good summary is given in this [Twitter thread](https://twitter.com/instrumenthull/status/1487469316010389516?s=20&t=iBn_tVYqyo_hcZJ-RnVoLQ).

### Describe the solution you'd like

Translate this [R script](https://gist.github.com/grantmcdermott/7d8f9ea20d2bbf54d3366f5a72482ad9) to Python and integrate the functionality into the `bootstrap` function. Possibly use a `bayesian=True` flag or a `type="bayesian"` argument.

**Comment by janosg** [comment]
Not planned for now.
