### ISSUE TITLE
Styling of yaml files

### ISSUE THREAD

**Issue by hmgaudecker** [OpenSourceEconomics/estimagic#426]
### Current situation

Consistent styling is helpful for many reasons. Also applies to yaml files, particularly when comparing settings across projects.

Styling of yaml files is ad-hoc.
 
### Desired Situation

Style yaml files automatically.

### Proposed implementation

Add yamlfix and yamllint hooks as described [here](https://github.com/OpenSourceEconomics/estimagic/pull/420#issuecomment-1382756450) , fix settings so that it they work in estimagic.

Based on [this](https://github.com/OpenSourceEconomics/estimagic/pull/420#issuecomment-1382756450) conversation, I had been under the impression that these were added in #420, but they did not appear. 

Adding them is not fully trivial. Reasons AFAICT:

- [ ] Fix settings of yamlfix so that yamllint does not complain when test files are changed.
- [ ] Align the output of `.envs/update_envs.py` with what yamlfix will do (e.g., six spaces for the pip-installed packages, align settings yamlfix/yamllint for inline comments)

**Comment by janosg** [comment]
I also thought it was done as part of #420. @timmens can you have a look when you are back? It is not urgent!

**Comment by hmgaudecker** [comment]
No worries! Happy to look into a PR together, but no rush.

**Comment by hmgaudecker** [comment]
I just pushed the `yaml-linting` branch. I already added the hooks and ran them on files that don't cause issues. 

The two items from the to-do list above are still open.
