### ISSUE TITLE
Add standard errors for MSM / GMM.

### ISSUE THREAD

**Issue by hmgaudecker** [OpenSourceEconomics/estimagic#43]
Now that the numerical differentiation is there, it would be great to add the matrix algebra bit for (nonlinear) GMM or the Method of Simulated Moments.

Section 13.25 / Page 525 of [Bruce Hansen's book](https://www.ssc.wisc.edu/~bhansen/econometrics/Econometrics.pdf) should do, else [Davidson / MacKinnon](http://qed.econ.queensu.ca/ETM/) is probably an even better reference, but I do not have a copy on my desk right now.

I am happy to provide guidance, I suppose @MaxBlesch you know your way around the code enough? Else we need to remember that thankfully, @janosg will not take his laptop along on vacation this time around!

**Comment by janosg** [comment]
The code should go into a module called `moment_covs` in the `inference` directory. It should be similar to  the functions in `likelihood_covs` in the following sense:

- One function for each covariance method you implement. 
- The docstring should document all inputs and references to textbooks etc and briefly describe the advantages or disadvantages of the method (e.g. finite sample properties, numerical stability, ...)
- Don't call numerical derivatives inside the functions. Just take the gradients / jacobians / hessians you need as inputs but describe them very thoroughly, such that a user would exactly know which function he has to differentiate. 
- All functions should work with numpy arrays and DataFrames as inputs (this is probably not yet the case in likelihood_covs, but could be part of your PR).

Later we might add wrappers that combine several steps, but it is important to have the building blocks separately. 

As always: write unit tests for all functions!

I'm still available for questions until Friday.

**Comment by hmgaudecker** [comment]
How are we progressing on this one, @MaxBlesch ? Any help needed? I did not get around to anything last week but will have time to look over it this week. Would be really great to have something by Thursday.

**Comment by MaxBlesch** [comment]
It was the same for me last week. I just finished my draft on the first implementation. I do have some questions, regarding implementation but also regarding comprehension. Hope we can meet this week?

**Comment by hmgaudecker** [comment]
Cool. Tomorrow 11:30h?

**Comment by MaxBlesch** [comment]
I meet tomorrow at 11 with Philipp and then we work the day on robust Zurcher. Maybe Wednesday or Thursday?

**Comment by hmgaudecker** [comment]
Looks pretty good to me, thanks. 

Especially for MSM, however, it would be nice to (also?) have a version without reference to the N dimension. 

I.e., please factor out the second block in `gmm_cov` (starting with "`bread = `") into a separate function `sandwich_cov(Q, W, Omega, nobs)`.

**Comment by hmgaudecker** [comment]
Closed via 3d430c6c3853
