### ISSUE TITLE
logging and checkpointing

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/estimagic#45]
We need the ability for long estimations runs on compute servers. The use of the dashboard is not an option there. We need a lightweight logging infrastructure that writes information about the estimation progress to disk. This allows to monitor the optimization as it progresses and also to potentially restart at an intermediate outcome.

**Comment by hmgaudecker** [comment]
In case @janosg is still away from any digital infrastructure: That is all underway.

**Comment by peisenha** [comment]
@raholler , @mo2561057 and @peisenha can't wait .... in both senses of the words :)

**Comment by raholler** [comment]
it was not communicated to me, that this is hiqh priority before. Won't have time to dig into that before first week of september.

**Comment by hmgaudecker** [comment]
It wasn't until @peisenha apparently felt an urgent need! Thanks!

**Comment by janosg** [comment]
Until @raholler has time for this it is probably best if you just add the logging directly to your objective function. Assuming your criterion function was called `crit_func` you could do something like this (untested):

```python
def logging_crit_func(params, args, counter=np.zeros(1)):
    params.to_pickle(f"{counter}.pickle")
    with_open("text_file.txt", "w") as file:
        file.write(params.to_string())
    counter += 1
    return crit_func(params, args)
    
```
The pickle files are there for restarting. The text file can be used for monitoring in the same way as the old respy did. 

@tobiasraabe will try to find out how to open a dashboard that runs on a remote server in a local browser and will post here if he finds something. It should work similarly as running a jupyter notebook, which will probably be part of the hackathon presentation by @hmgaudecker tomorrow.

**Comment by janosg** [comment]
Thanks to work by @tobiasraabe, an estimagic dashboard running on a remote server can now (version 0.0.12) be opened in a local browser just like a jupyter notebook. If you are interested, check out the [documentation](https://estimagic.readthedocs.io/en/master/dashboard.html#on-a-remote-server)

**Comment by hmgaudecker** [comment]
Good that I forgot to delete the line claiming that (falsely until today) in the makeover of the slides 😁

**Comment by tobiasraabe** [comment]
Done in #102.
