### ISSUE TITLE
update `siunitx_warning` for estimation_table

### ISSUE THREAD

**Issue by ChristianZimpelmann** [OpenSourceEconomics/estimagic#458]
### Bug description

In `siunitx_warning` and in the estimation_table how-to, we state that the user should add the following to their tex file:

```latex
\sisetup{
   input-symbols            = (),
   table-align-text-post    = false,
   group-digits             = false,
}
```

However, I needed the following specification to have the tex file compile without error:

```latex
\sisetup{
   input-symbols            = (),
   table-align-text-pre     = false,
   table-align-text-post    = false,
   group-digits             = false,
}
```

**Comment by janosg** [comment]
Would be interesting to know if this is tied to a specific feature of the table you had or a change in `estimation_table`. I am pretty sure, the old version worked in a few projects. 

I don't understand much about `sisetup`. I am happy to change it.

**Comment by ChristianZimpelmann** [comment]
Somehow, I cannot reproduce the error right now. Let's close it and I might get back to it when I get the error again. Sorry for the noise!
