### ISSUE TITLE
Replace `DateFrame.applymap` with `DataFrame.map` (in estimation_table)

### ISSUE THREAD

**Issue by ChristianZimpelmann** [OpenSourceEconomics/estimagic#470]
pandas 2.1. deprecated DataFrame.applymap
> New in version 2.1.0: DataFrame.applymap was deprecated and renamed to DataFrame.map. 

The current `estimation_table` uses `applymap` in several occasions and produces many DeprecationWarnings.

### Describe the solution you'd like

- replace with `.map`
- as long as we still support pandas 2.0, we should probably ignore the warning

**Comment by hmgaudecker** [comment]
@timmens, could you have a look at whether you want to do a conditional import or stop supporting older pandas? I presume estimagic is used a lot in conjunction with pytask and it is very annoying to sift through pages of deprecation warnings before being able to see what actually happened with the build.
