### ISSUE TITLE
Make closed form derivatives optional for gradient based nlopt algorithms

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/estimagic#51]
## Current Situation

gradient based nlopt algorithm require a user specified gradient function

## Goal

Use numerical differentiation when the user does not specify one

## Open questions

- Should we use the estimagic functions for numerical derivatives or the ones from [pygmo](https://esa.github.io/pagmo2/docs/python/utils/py_gh_utils.html). Pygmo has probably a version that is imprecise but very fast, which is what we need here.

**Comment by tobiasraabe** [comment]
Solved in #102, right?

**Comment by janosg** [comment]
yes
