### ISSUE TITLE
maximize and minimize should return just one result

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/estimagic#54]
## Current Behavior

The functions return a params DataFrame and a json serializable dictionary with other information about the optimization

## Desired Behavior

Have one results object that contains all the information. This has the advantage that just one object has to be passed into visualization functions like the comparison plot. 

### Add metadata to the params DataFrame 

This would be the nicest interface and very useful in many places of estimagic, but it is probably impossible to implement. Of course we could add attributes to the DataFrame like [here](https://stackoverflow.com/questions/14688306/adding-meta-information-metadata-to-pandas-dataframe) but they wouldn't be preserved after operations that make copies (merging, ...). There was an [issue](https://stackoverflow.com/questions/14688306/adding-meta-information-metadata-to-pandas-dataframe) to change that, but my impression is that it won't be part of pandas soon. We don't want to make a custom subclass of DataFrame.

### Put the DataFrame in the dictionary

The only problem here is that we lose the ability to save the dictionary as json. To do so, one would first have to make a copy of the dictionary without the DataFrame

### Collect dictionary and df in a namedtuple (proposed solution)

The fields could be named `params` and `info`. While this is similar to putting the df in a dictionary, I think it has several advantages:

- It is easier to split it into the json serializable dict and the df
- Its two components are very simple and well known (a flat dict and the df). So it's very clear which operations can be done with them and there would never be a surprising loss of metadata
- It is immutable, so people could not accidentally combine the params and info from different optimizations

@tobiasraabe @roecla I think I see this much clearer now than yesterday. So if you agree we could just assume this new interface in #26 and then implement it in the optimization in a separate PR.

**Comment by tobiasraabe** [comment]
👍 Agree.

**Comment by roecla** [comment]
I like the idea of the named tuple. This would allow us to very flexibly return everything possibly interesting in the "internal" optimization output - no matter which optimizer library was used. Especially if ``info`` is a dictionary and we come up with a good set of keys that unifies the outputs from the different libraries. We could also easily tag on additional information collected outside the optimizer library (e.g. for the purpose of debugging).

**Regarding serializability**

1. I wonder if it's really necessary to stick to ``params`` as a DataFrame. I cannot think of a case at the moment where ``params.to_dict()`` would cause us to lose any information. Of course, that would mean converting it back in many cases (such as the comparison plot) but that might be worth it. 
2. In case we decide to return ``params`` as a dictionary: [Named tuples are not easily serializable](https://stackoverflow.com/questions/5906831/serializing-a-python-namedtuple-to-json) so given that there are only two entries in the tuple we might want to skip the naming step.

Moving to the (named) tuple should also allow us to get rid of the duplication now present in what the optimization returns. Right now both ``res_dict`` and ``params`` contains the final parameter vector.

**Comment by janosg** [comment]
Regarding 1: No loss of information, but you can't do anything with such a dictionary. Also, I really want to convince people that there is nothing better than a DataFrame to represent and manipulate parameter vectors.

Yes, it is true that we can get rid of the duplication. Good observation!

**Comment by janosg** [comment]
The returned result should also contain the constraints.

**Comment by tobiasraabe** [comment]
#102 implements a ``results`` dictionary which contains harmonized fields which are the same across optimizers and other fields.

We thought about implementing a nice ``__repr__`` method which turns the dictionary into a beautiful screen output, but it is delayed for now.
