### ISSUE TITLE
Allow for user specified derivative functions during optimization

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/estimagic#56]
## Current situation

We do pass a user specified gradient or hessian functions through to to the optimizer, but this function will be called with an internal parameter vector.

## Desired situation

A user should not have to bother about the internals and be able to provide a gradient or hessian functions that work on an external parameter vector. Estimagic converts this automatically into a corresponding function that operates on an internal parameter vector.

## Implementation

We will have to write closed form derivative functions for the reparametrization steps (from_internal) and use the chain rule. Everyone who has seen me taking derivatives knows that I will need help with the math. The most difficult one should be the cholesky transformation, but below I post some references. 

## Some references

- [Theory](https://arxiv.org/abs/1602.07527)
- Of course there is a [python implementation](https://github.com/imurray/chol-rev)

**Comment by hmgaudecker** [comment]
Can't you just--for most of the stuff--just run the constraints functions through sympy?

**Comment by janosg** [comment]
I have never worked with sympy but will check it out.

**Comment by janosg** [comment]
This is done in estimagic 0.1. Unfortunately we had to go for closed form implementations because jax does not run on windows and sympy could not do what we need.
