### ISSUE TITLE
Improve gradient based optimization

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/estimagic#58]
## Notes

This might be a controversial issue. @tobiasraabe, @hmgaudecker, @roecla, @peisenha feel free to comment. If we implement this, #51 will be solved on the way.

## Current Situation

If no gradient is specified, most optimizers will do some form of numerical differentiation. Since we don't influence this, we don't get any gradient information out and can't distinguish between function evaluations for gradient calculation and actually interesting function evaluations

## Desired Situation

- Distinguish between function evaluations done for gradient calculation (those should not be reflected in the convergence or fitness plots and probably don't have to be saved and logged) and actual function evaluations during the optimization
- Plot the evolution of the gradient in the dashboard (similar to the parameter convergence plots)
- Maybe: implement custom termination criteria based on gradient

## Possible Implementation

Write a function that uses the fast (but not too precise) gradient functions from pygmo to calculate a numerical gradient. Pass this to the optimizers as custom gradient function. Inside the gradient function we would call a slightly different version of the `internal_criterion` that does not update the convergence plot in the dashboard and has a different iteration counter. After each evaluation, the gradient information is sent to the dashboard.

## Discussion

The main disadvantage is that we could not guarantee to reproduce the same results as when the original library with their default numerical derivative is called. This should not make a difference and if it does, the optimization problem is probably very problematic anyways, but it is something we have to discuss.

**Comment by hmgaudecker** [comment]
I would think that all three optimization libraries (scipy, pygmo, tao) have some sort of callback implemented that allows you to do exactly this at much lower cost (both in terms of behavior and in terms of coding it up). If I am not mistaken POUNDERs will, for example, adjust step sites dynamically, starting with something like 1/100 of the parameters initially and making them smaller as you get closer to the optimum.

For POUNDERs I am rather sure that such functionality is around.

**Comment by tobiasraabe** [comment]
This is solved in #102.

**Comment by janosg** [comment]
We now use our own implementations because none of the libraries could parallelize the gradient evaluations and because we have fast and robust numerical derivatives for inference anyways. 

Pounders is not affected because it only calculates closed form derivatives of surrogate models for the trustregion subproblem.
