### ISSUE TITLE
Documentation of corner cases in constraints

### ISSUE THREAD

**Issue by hmgaudecker** [OpenSourceEconomics/estimagic#64]
This occurred to me in the context of thinking about #61: What happens if you set the upper bound and lower bound of a parameter to be equal but don't specify it to be fixed? Will it

1. be treated as a fixed parameter by estimagic or 
2. left to the optimizer to handle or
3. raise an error or
4. ?

I could not find it in the docs and don't have time to play around. 

My 2c if behavior has not been set explicitly: I would suggest 3 - requiring the user to do it the right way seems not be too much to ask... In any case, 2. is evil (you would see "weird" stuff if the code pondered in #57 was implemented -- rather fail early).

**Comment by janosg** [comment]
It will raise an error. In the beginning I had implemented 1) but then switched for the exact reasons you mentioned. I'll extend the documentation accordingly.

**Comment by janosg** [comment]
I included this into my to-do list of #63 and close it here.
