### ISSUE TITLE
autodoc documentation of the differentiation module fails

### ISSUE THREAD

**Issue by roecla** [OpenSourceEconomics/estimagic#66]
When trying to compile the estimagic documentation with Sphinx I get the following warnings:

```
WARNING: autodoc: failed to import function 'differentiation.gradient' from module 'estimagic.differentiation'; the following exception was raised:
No module named 'numdifftools'
WARNING: autodoc: failed to import function 'differentiation.hessian' from module 'estimagic.differentiation'; the following exception was raised:
No module named 'numdifftools'
WARNING: autodoc: failed to import function 'differentiation.jacobian' from module 'estimagic.differentiation'; the following exception was raised:
No module named 'numdifftools'
```

In the rendered documentation the documentation of the mentioned functions are missing.

I made sure that ``numdifftools`` is in my environment. Maybe it has to be added to sphinx in some way extra?

**Comment by hmgaudecker** [comment]
How about the other way around -- are you sure sphinx is in the environment and the right one is called?

Sphinx will just import stuff like any other Python process, so no extra settings needed...

**Comment by roecla** [comment]
Yes, that's it. Updating the environment solved it. Thanks!
