### ISSUE TITLE
Ignore pandas PerformanceWarning

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/estimagic#81]
## Current Situation

Most estimagic criterion functions will produce the following warning:  ``PerformanceWarning: indexing past lexsort depth may impact performance`` which can always be ignored because params is way too small for this to be relevant. 

See [here](https://stackoverflow.com/questions/54307300/what-causes-indexing-past-lexsort-depth-warning-in-pandas) for more info. 

# Desired situation

The warning is disabled at the beginning of minimize.

**Comment by vgangaprasad** [comment]
Hi Janos and Hans, if we add the following then the warnings will be ignored.

**import warnings
warnings.simplefilter(action='ignore', category=pd.errors.PerformanceWarning)**

Do you want to add this in all notebooks?

Thanks,
Vijay

**Comment by janosg** [comment]
Hi Vijay,

thanks for your tip. Also, welcome to estimagic! 

instead of adding it to the notebooks (i.e. user code) we want to add it to the beginning of the [``minimize`` function](https://github.com/OpenSourceEconomics/estimagic/blob/851149d62d6a88d00b5aae1b9f5bb3422290e40a/estimagic/optimization/optimize.py#L94). That way the user doesn't have to bother.

**Comment by vgangaprasad** [comment]
Thanks Janos. I will try changing the minimize function.

**Comment by janosg** [comment]
Thanks a lot! In case you haven't seen it, here is a description of our workflow: https://estimagic.readthedocs.io/en/master/contributing/index.html
