### ISSUE TITLE
Do not use db as abbreviation for dashboard.

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/estimagic#98]
## Current situation

we use `db` as abbreviation for dashboard, for example in `db_options`. However, for most people `db` is short for database and now that we have a database this becomes problematic. 

## Solution 1:

Write it out everywhere. This might, however, lead to very long variable names in some internal functions.

## Solution 2: 

Rename the dashboard to something that can be abbreviated or is shorter. Does anyone have a good idea? If so, please post here. So far I only came up with `magic_board`, abbreviated as `mb`.

**Comment by ChristianZimpelmann** [comment]
How about `dash` as abbreviation for `dashboard`?

**Comment by janosg** [comment]
I like it. If nobody else has a good idea I would do that.

**Comment by roecla** [comment]
I would suggest `monitor(ing)`. A little longer than `dash` but less confusing outside the dashboard code base. Also I'd say it describes better what the dashboard does. Could of course also be abbreviated further where necessary.

**Comment by janosg** [comment]
Some people might look directly at the database to monitor an optimization. So monitoring is probably not precise enough. I prefer what Christian proposed.

**Comment by janosg** [comment]
Will be done as part of #132
