### ISSUE TITLE
make all return arguments from optimizers acessible

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/estimagic#99]
### Current situation

Not all return arguments of all optimizers, in my case `nlopt`, are returned by `estimagic`. See here https://github.com/OpenSourceEconomics/estimagic/blob/55c2d990e0e0206005880eaeb47a7f10cd25a46f/estimagic/optimization/optimize.py#L554

### Desired Situation

All return arguments of the optimizers are also returned by `estimagic`

**Comment by janosg** [comment]
This is a duplicate of #5 which was on @tobiasraabe's to-do list for this week anyways. Therefore, I close it here. The reason why it was open for so long is that it's quite hard to get this information from pygmo.
